Add `PlayerChanged` to synced Lua
spring/spring pull request #369
Opened 2018-03-12 13:23 UTC by sprunk

Except for demo-watching specs, when these do something it's still unsynced only

2018-03-12 18:20 UTC, rtri commented
This is moving in the wrong direction for my taste, I'd add a SyncedPlayerChanged event.

2018-03-12 19:34 UTC, sprunk commented
Alright.

2022-01-11 21:38 UTC, abma commented
@sprunk:

as i only partly understand this change: what problem does this solve?

2022-01-12 08:22 UTC, sprunk commented
Synced currently doesn't know about the PlayerChanged event, so you can't do things when somebody disconnects or reconnects (for example a gadget that gives the abandoned units so somebody can control them, and then returns them on reconnect). I believe it is unavailable because people watching a replay can also generate the event, which is why the patch makes a new callin (cutting replay-watching spectators from regular PlayerChanged would hurt unsynced gadgets and LuaUI, and exposing them to synced would open up the possibility of a desync).

2022-01-12 08:57 UTC, abma commented
I hopefully merged correctly?!

2022-01-12 10:17 UTC, sprunk commented
I copied the explanation to the code as a comment: 747b49cd6bedc672283b3fd691b6e8143e8cd5bb

2022-01-12 19:17 UTC, abma requested changes

2022-01-12 19:17 UTC, abma commented on rts/Net/NetCommands.cpp
> +						LOG("Skirmish AI \"%s\" (ID:%i), which controlled team %i is now dead", aiInstanceName.c_str(), aiNum, aiTeamId);
rts/Net/NetCommands.cpp:1296:79: error: use of undeclared identifier 'aiInstanceName'

  ...AI \"%s\" (ID:%i), which controlled team %i is now dead", aiInstanceName...

2022-01-12 19:17 UTC, abma commented on doc/changelog.txt
> +=======
my fault: should be removed

2022-01-13 21:14 UTC, abma commented
https://github.com/spring/spring/commit/aa7a9972a26c15cb41d9d438fc457a86d58f7630

2022-01-13 21:14 UTC, closed without merging